=== paypal/load-watcher/pkg/watcher/schema/watcher-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "timestamp": {
      "type": "integer"
    },
    "window": {
      "type": "object",
      "properties": {
        "duration": {
          "type": "string"
        },
        "start": {
          "type": "integer"
        },
        "end": {
          "type": "integer"
        }
      },
      "required": [
        "duration",
        "start",
        "end"
      ]
    },
    "source": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "patternProperties": {
        "^[0-9]+$": {
          "type": "object",
          "properties": {
            "metrics": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "operator": {
                      "type": "string"
                    },
                    "rollup": {
                      "type": "string"
                    },
                    "value": {
                      "type": "integer",
                      "description": "percentage value"
                    }
                  },
                  "required": [
                    "name",
                    "type",
                    "operator",
                    "rollup",
                    "value"
                  ]
                },
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    },
                    "operator": {
                      "type": "string"
                    },
                    "rollup": {
                      "type": "string"
                    },
                    "value": {
                      "type": "integer",
                      "description": "percentage value"
                    }
                  },
                  "required": [
                    "name",
                    "type",
                    "operator",
                    "rollup",
                    "value"
                  ]
                }
              ]
            },
            "tags": {
              "type": "object"
            },
            "metadata": {
              "type": "object",
              "properties": {
                "dataCenter": {
                  "type": "string"
                },
                "pool": {
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "metrics"
          ]
        }
      }
    }
  },
  "required": [
    "timestamp",
    "window",
    "source",
    "data"
  ]
}

=== paypal/load-watcher/pkg/watcher/schema/watcher-example.json
{
  "timestamp": 1556987522,
  "window": {
    "duration": "15m",
    "start": 1556984522,
    "end": 1556985422
  },
  "source": "InfluxDB",
  "data": {
    "node-1": {
      "metrics": [
        {
          "name": "host.cpu.utilisation",
          "type": "cpu",
          "rollup": "AVG",
          "value": 20
        },
        {
          "name": "host.memory.utilisation",
          "type": "memory",
          "rollup": "STD",
          "value": 5
        }
      ],
      "tags": {},
      "metadata": {
        "dataCenter": "data-center-1",
        "pool": "critical-apps"
      }
    },
    "node-2": {
      "metrics": [
        {
          "name": "host.cpu.utilisation",
          "type": "cpu",
          "rollup": "AVG",
          "value": 20
        },
        {
          "name": "host.memory.utilisation",
          "type": "memory",
          "rollup": "STD",
          "value": 5
        }
      ]
    },
    "metadata": {
      "dataCenter": "data-center-2",
      "pool": "light-apps"
    },
    "tags": {}
  }
}
